### ISSUE TITLE
"Banzem: AutoCrystal, Quiver, SilentXP"

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [3000IQPlay/Atrium-Phobos-Edition#2]
Just a heads up, Banzem (mohalks old client before indium) was a phobos skid and those modules are most likely from perry phobos leak. Should give credit for that. and the AutoCrystal is just modified Phobos ca with Perry phobos renders. Oh and, The quiver is also from perry phobos leak,.

**Comment by 3000IQPlay** [comment]
> 

thx for info
