### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by ghost** [3000IQPlay/Atrium-Phobos-Edition#4]
Is there a single thing in this that is custom? The code is so bad & I have yet to see anything custom everything is skidded if there is at least 1 line of custom code please inform me I will review it.

**Comment by 3000IQPlay** [comment]
> Is there a single thing in this that is custom? The code is so bad & I have yet to see anything custom everything is skidded if there is at least 1 line of custom code please inform me I will review it.

This project was a big mix of code from other clients. Thats why i want to make Atrium+

**Comment by Tarkan-Zarrouk** [comment]
> Is there a single thing in this that is custom? The code is so bad & I have yet to see anything custom everything is skidded if there is at least 1 line of custom code please inform me I will review it.

everything in the client is either skidded from oyvey or from one of perry phobos leaks.

**Comment by M3gaPixel** [comment]
eyes are bleeding yesyes
