### ISSUE TITLE
Stop using Phobos.

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [3000IQPlay/Atrium-Phobos-Edition#7]
Hey uh,

Just want to give you a heads up for whoever is running this garbage but, stop using phobos and fix your the errors in your client.
There's over 18k errors when I pressed commit & push to main. I just wan't to give you a heads up  about that. 
If you really want to stick with phobos base just learn java and try to make something custom.
https://www.tutorialspoint.com/java/java_tutorial.pdf here's a little pdf incase you want to learn a bit about Java. It's 30+ pages but I doubt you care and it's currently 5 am and I have nothing to do so I'm writing this lmfao

**Comment by ghost** [comment]
> Hey uh,
> 
> Just want to give you a heads up for whoever is running this garbage but, stop using phobos and fix your the errors in your client. There's over 18k errors when I pressed commit & push to main. I just wan't to give you a heads up about that. If you really want to stick with phobos base just learn java and try to make something custom. https://www.tutorialspoint.com/java/java_tutorial.pdf here's a little pdf incase you want to learn a bit about Java. It's 30+ pages but I doubt you care and it's currently 5 am and I have nothing to do so I'm writing this lmfao

https://www.w3schools.com/java/default.asp
has all the necessary info in it and huge stuff ofc there's more stuff in Java but this covers all the main/huge/needed stuff in Java

**Comment by master7720** [comment]
> Hey uh,
> 
> Just want to give you a heads up for whoever is running this garbage but, stop using phobos and fix your the errors in your client. There's over 18k errors when I pressed commit & push to main. I just wan't to give you a heads up about that. If you really want to stick with phobos base just learn java and try to make something custom. https://www.tutorialspoint.com/java/java_tutorial.pdf here's a little pdf incase you want to learn a bit about Java. It's 30+ pages but I doubt you care and it's currently 5 am and I have nothing to do so I'm writing this lmfao

^^^^

**Comment by Tarkan-Zarrouk** [comment]
> > Hey uh,
> > Just want to give you a heads up for whoever is running this garbage but, stop using phobos and fix your the errors in your client. There's over 18k errors when I pressed commit & push to main. I just wan't to give you a heads up about that. If you really want to stick with phobos base just learn java and try to make something custom. https://www.tutorialspoint.com/java/java_tutorial.pdf here's a little pdf incase you want to learn a bit about Java. It's 30+ pages but I doubt you care and it's currently 5 am and I have nothing to do so I'm writing this lmfao
> 
> https://www.w3schools.com/java/default.asp has all the necessary info in it and huge stuff ofc there's more stuff in Java but this covers all the main/huge/needed stuff in Java

Yep. 
Going to buy the document soon™️
