### ISSUE TITLE
STOP TRYING TO RUN GRADLE WITH PHOBOS 

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [3000IQPlay/Atrium-Phobos-Edition#8]
Run ./gradlew build

> Configure project :
This mapping 'stable_39' was designed for MC 1.12! Use at your own peril.
WARNING: You are using an unsupported version of ForgeGradle.
Please consider upgrading to ForgeGradle 5 and helping in the efforts to get old versions working on the modern toolchain.
See https://gist.github.com/TheCurle/fe7ad3ede1[8](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:8)8cbdd15c235cc75d52d4a for more info on contributing.
Found AccessTransformer: atrium_at.cfg
Download https://maven.minecraftforge.net/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom
Download https://repo.spongepowered.org/repository/maven-public/club/minnced/java-discord-rpc/2.0.2/java-discord-rpc-2.0.2.pom
Download https://repo.spongepowered.org/repository/maven-public/org/spongepowered/mixin/0.7.11-SNAPSHOT/maven-metadata.xml
Download https://repo.spongepowered.org/repository/maven-public/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-20180703.121122-1.pom
Download https://maven.minecraftforge.net/junit/junit/4.10/junit-4.10.pom
Download https://repo.spongepowered.org/repository/maven-public/club/minnced/discord-rpc-release/v3.4.0/discord-rpc-release-v3.4.0.pom
Download https://maven.minecraftforge.net/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.pom
Download https://maven.minecraftforge.net/org/hamcrest/hamcrest-parent/1.1/hamcrest-parent-1.1.pom
Download https://repo.spongepowered.org/repository/maven-public/club/minnced/java-discord-rpc/2.0.2/java-discord-rpc-2.0.2.jar
Download https://maven.minecraftforge.net/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
Download https://maven.minecraftforge.net/junit/junit/4.10/junit-4.10.jar
Download https://repo.spongepowered.org/repository/maven-public/club/minnced/discord-rpc-release/v3.4.0/discord-rpc-release-v3.4.0.jar
Download https://maven.minecraftforge.net/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
Download https://repo.spongepowered.org/repository/maven-public/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-20180703.121122-1.jar

> Task :deobfCompileDummyTask
> Task :deobfProvidedDummyTask
> Task :sourceApiJava
> Task :compileApiJava NO-SOURCE
> Task :processApiResources NO-SOURCE
> Task :apiClasses UP-TO-DATE
> Task :sourceMainJava

> Task :compileJava
Potential refmap conflict. Duplicate refmap name mixins.atrium.refmap.json specified for sourceSet main, already defined for sourceSet main
Note: SpongePowered MIXIN Annotation Processor Version=0.7.11
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
Note: Loading searge mappings from /home/runner/.gradle/caches/minecraft/de/oceanlabs/mcp/mcp_stable/3[9](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:9)/1.[12](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:12).2/srgs/mcp-srg.srg
Note: Loading notch mappings from /home/runner/.gradle/caches/minecraft/de/oceanlabs/mcp/mcp_stable/39/1.12.2/srgs/mcp-notch.srg
Note: Writing refmap to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/compileJava-refmap.json
/home/runner/work/Atrium/Atrium/build/sources/main/java/me/_3000IQPlay/atrium/mixin/mixins/MixinEntity.java:[16](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:16)8: warning: @Overwrite is missing an @author tag
    public void move(MoverType type, double x, double y, double z) {
                ^
/home/runner/work/Atrium/Atrium/build/sources/main/java/me/_[30](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:30)00IQPlay/atrium/mixin/mixins/MixinEntity.java:168: warning: @Overwrite is missing an @reason tag
    public void move(MoverType type, double x, double y, double z) {
                ^
Note: Writing refmap to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/compileJava-refmap.json
Note: Writing searge output SRGs to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/mcp-srg.srg
Note: Writing notch output SRGs to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/mcp-notch.srg

> Task :compileJava FAILED

/home/runner/work/Atrium/Atrium/build/sources/main/java/me/_3000IQPlay/atrium/features/modules/combat/HoleFiller.java:[60](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:60): error: cannot find symbol
    private Offhand.Mode offhandMode = Offhand.Mode.CRYSTALS;
                   ^
  symbol:   class Mode
  location: class Offhand
Note: Writing refmap to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/compileJava-refmap.json
Note: Writing refmap to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/compileJava-refmap.json
Note: Writing searge output SRGs to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/mcp-srg.srg
Note: Writing notch output SRGs to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/mcp-notch.srg
1 error
2 warnings

FAILURE: Build failed with an exception.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 5 executed
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 16s
Error: Process completed with exit code 1.
LOOK AT YOUR FUCKING ERRORS HOLY SHIT I'm DONE

**Comment by 3000IQPlay** [comment]
> Run ./gradlew build
> 
> > Configure project :
> > This mapping 'stable_39' was designed for MC 1.12! Use at your own peril.
> > WARNING: You are using an unsupported version of ForgeGradle.
> > Please consider upgrading to ForgeGradle 5 and helping in the efforts to get old versions working on the modern toolchain.
> > See [https://gist.github.com/TheCurle/fe7ad3ede1[8](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:8)8cbdd15c235cc75d52d4a](https://gist.github.com/TheCurle/fe7ad3ede1%5B8%5D(https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:8)8cbdd15c235cc75d52d4a) for more info on contributing.
> > Found AccessTransformer: atrium_at.cfg
> > Download https://maven.minecraftforge.net/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.pom
> > Download https://repo.spongepowered.org/repository/maven-public/club/minnced/java-discord-rpc/2.0.2/java-discord-rpc-2.0.2.pom
> > Download https://repo.spongepowered.org/repository/maven-public/org/spongepowered/mixin/0.7.11-SNAPSHOT/maven-metadata.xml
> > Download https://repo.spongepowered.org/repository/maven-public/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-20180703.121122-1.pom
> > Download https://maven.minecraftforge.net/junit/junit/4.10/junit-4.10.pom
> > Download https://repo.spongepowered.org/repository/maven-public/club/minnced/discord-rpc-release/v3.4.0/discord-rpc-release-v3.4.0.pom
> > Download https://maven.minecraftforge.net/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.pom
> > Download https://maven.minecraftforge.net/org/hamcrest/hamcrest-parent/1.1/hamcrest-parent-1.1.pom
> > Download https://repo.spongepowered.org/repository/maven-public/club/minnced/java-discord-rpc/2.0.2/java-discord-rpc-2.0.2.jar
> > Download https://maven.minecraftforge.net/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
> > Download https://maven.minecraftforge.net/junit/junit/4.10/junit-4.10.jar
> > Download https://repo.spongepowered.org/repository/maven-public/club/minnced/discord-rpc-release/v3.4.0/discord-rpc-release-v3.4.0.jar
> > Download https://maven.minecraftforge.net/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar
> > Download https://repo.spongepowered.org/repository/maven-public/org/spongepowered/mixin/0.7.11-SNAPSHOT/mixin-0.7.11-20180703.121122-1.jar
> 
> > Task :deobfCompileDummyTask
> > Task :deobfProvidedDummyTask
> > Task :sourceApiJava
> > Task :compileApiJava NO-SOURCE
> > Task :processApiResources NO-SOURCE
> > Task :apiClasses UP-TO-DATE
> > Task :sourceMainJava
> 
> > Task :compileJava
> > Potential refmap conflict. Duplicate refmap name mixins.atrium.refmap.json specified for sourceSet main, already defined for sourceSet main
> > Note: SpongePowered MIXIN Annotation Processor Version=0.7.11
> > Note: ObfuscationServiceMCP supports type: "searge"
> > Note: ObfuscationServiceMCP supports type: "notch"
> > Note: Loading searge mappings from /home/runner/.gradle/caches/minecraft/de/oceanlabs/mcp/mcp_stable/3[9](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:9)/1.[12](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:12).2/srgs/mcp-srg.srg
> > Note: Loading notch mappings from /home/runner/.gradle/caches/minecraft/de/oceanlabs/mcp/mcp_stable/39/1.12.2/srgs/mcp-notch.srg
> > Note: Writing refmap to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/compileJava-refmap.json
> > /home/runner/work/Atrium/Atrium/build/sources/main/java/me/_3000IQPlay/atrium/mixin/mixins/MixinEntity.java:[16](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:16)8: warning: @overwrite is missing an @author tag
> > public void move(MoverType type, double x, double y, double z) {
> > ^
> > /home/runner/work/Atrium/Atrium/build/sources/main/java/me/_[30](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:30)00IQPlay/atrium/mixin/mixins/MixinEntity.java:168: warning: @overwrite is missing an @Reason tag
> > public void move(MoverType type, double x, double y, double z) {
> > ^
> > Note: Writing refmap to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/compileJava-refmap.json
> > Note: Writing searge output SRGs to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/mcp-srg.srg
> > Note: Writing notch output SRGs to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/mcp-notch.srg
> 
> > Task :compileJava FAILED
> 
> /home/runner/work/Atrium/Atrium/build/sources/main/java/me/_3000IQPlay/atrium/features/modules/combat/HoleFiller.java:[60](https://github.com/3000IQPlay/Atrium/runs/5013278300?check_suite_focus=true#step:6:60): error: cannot find symbol private Offhand.Mode offhandMode = Offhand.Mode.CRYSTALS; ^ symbol: class Mode location: class Offhand Note: Writing refmap to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/compileJava-refmap.json Note: Writing refmap to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/compileJava-refmap.json Note: Writing searge output SRGs to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/mcp-srg.srg Note: Writing notch output SRGs to /home/runner/work/Atrium/Atrium/build/tmp/compileJava/mcp-notch.srg 1 error 2 warnings
> 
> FAILURE: Build failed with an exception.
> 
> Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0. Use '--warning-mode all' to show the individual deprecation warnings. See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings 5 actionable tasks: 5 executed
> 
> * What went wrong:
>   Execution failed for task ':compileJava'.
> 
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org/
> 
> BUILD FAILED in 16s Error: Process completed with exit code 1. LOOK AT YOUR FUCKING ERRORS HOLY SHIT I'm DONE

I think that no one uses this client so thats why i dont care about Atrium anymore (Only maded this public because i got bored with this skid and i didnt wanted to keep this in my pc)

**Comment by Tarkan-Zarrouk** [comment]
💀

**Comment by M3gaPixel** [comment]
if I fix all the shitty code and put up a pull request will you accept it? @3000IQPlay
